baseURL = 'https://oyyko-old-projects.github.io/blog-coder-copy/'
title = "Colin's Blog"
theme = "hugo-coder"
publishDir = "docs"
enableGitInfo = true
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 100
summaryLength = 3

[author]
  name = "Oyyko"
  github = "oyyko"
  linkedin = "col-z"
  email = "finalwind42@gmail.com"
  link = "https://oyyko-old-projects.github.io/blog-coder-copy/"

[params]
    tagline = "A C++ Programmer"
    description = "A C++ Programmer"
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = []  #Optional Customised CSS
    #favicon = ""
    #utterancesRepo = "username/repository"
    #utterancesIssueTerm = "pathname"
    homepageLength = 10

[markup]
  [markup.highlight]
    style = "monokai"
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
  # [markup.tableOfContents]
  #   startLevel = 1
  #   endLevel = 3
  #   ordered = false

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"
  weight = 1


[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts"
  weight = 2


# uncomment to enable the Tags link on the main toolbar
[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags"
  weight = 3

# [menu]
#   [[menu.main]]
#     weight = 1
#     identifier = "posts"
#     # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
#     pre = ""
#     # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
#     post = ""
#     name = "Posts"
#     url = "/posts/"
#     # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
#     title = ""
#   [[menu.main]]
#     weight = 2
#     identifier = "tags"
#     pre = ""
#     post = ""
#     name = "Tags"
#     url = "/tags/"
#     title = ""